Apr 1719 application outcome pass
SkillsFundingAgency/das-roatp-assessor pull request #42
Opened 2020-10-13 15:09 UTC by MarkFCain

2020-10-14 07:20 UTC, martin-hornsby commented on src/SFA.DAS.RoatpAssessor/SFA.DAS.RoatpAssessor.Web.UnitTests/Controllers/ModeratorOutcome/ModeratorOutcomeControllerTests.cs
> +            var command = new SubmitModeratorOutcomeConfirmationCommand("", "Yes");
Should probably be consistent and use string.Empty instead of ""

2020-10-14 07:20 UTC, martin-hornsby commented on src/SFA.DAS.RoatpAssessor/SFA.DAS.RoatpAssessor.Web.UnitTests/Controllers/ModeratorOutcome/ModeratorOutcomeControllerTests.cs
> +            var command = new SubmitModeratorOutcomeConfirmationCommand("", "Yes");
Should probably be consistent and use string.Empty instead of ""

2020-10-14 07:31 UTC, martin-hornsby requested changes

2020-10-14 07:31 UTC, martin-hornsby commented on src/SFA.DAS.RoatpAssessor/SFA.DAS.RoatpAssessor.Web/Controllers/Moderator/ModeratorOutcomeController.cs
> +                _logger.LogInformation($"Unable to save moderation outcome for applicationId: [{applicationId}]");
I think this should be a LogError rather than LogInformation as an error has occured and we'll want to see it in Kibana easier :)

2020-10-14 07:31 UTC, martin-hornsby commented on src/SFA.DAS.RoatpAssessor/SFA.DAS.RoatpAssessor.Web/Views/Dashboard/InModerationApplications.cshtml
> +                    await Html.RenderPartialAsync("DashboardNavigation.cshtml"); }
Could we use the .ASP Core: <partial> tag here?  @Html.RenderPartialAsync has been deprecated

2020-10-14 07:31 UTC, martin-hornsby commented on src/SFA.DAS.RoatpAssessor/SFA.DAS.RoatpAssessor.Web/Views/Dashboard/InModerationApplications.cshtml
> +                                                <strong class="das-tag">In moderation</strong>
Just want to check if just `das-tag` is okay here? In the dashboard we've also got `das-no-wrap`

2020-10-14 08:49 UTC, martin-hornsby approved these changes

2020-10-21 07:40 UTC, MarkFCain commented
merged in APR-1722

2020-10-21 07:40 UTC, closed without merging